import SeedToBottle from "./components/SeedToBottle";
import SideBySide from "./components/SideBySide";

export const METHODS = {
  "wood-pressed": {
    Banner: {
      image: "/banners/banner-wood-pressed.jpg",
      title: "Wood Pressed",
    },
    ColdPressedFlour: {
      title: "Wood Pressed Oil",
      description: "Authentic Goodness in Every Bundle",
      badge: "OUR METHODS · WOOD PRESSED OIL ",
      headline1: "PRESSED SLOW.",
      headline2: "POURED",
      headlineGold: "PURE",
      desc: "Wood pressing is a slower mechanical method of extracting oil from seeds. The oil is extracted through pressure, without solvent extraction, keeping the process simple and close to the traditional way of making oil.",
      btnPrimary: "Explore the Process",
      btnSecondary: "Shop Wood Pressed Oils",
      image: "/methods/wood-pressed-oil.jpg",
      stats: [
        { value: "18–19 RPM", label: "Slow Mechanical Pressing" },
        { value: "100%", label: "Chemical free" },
        { value: "100%", label: "Seed-Based Oil" },
      ],
    },

    SeedToBottle: {
      title: "Four Steps ",
      headline1: "From Seed to ",
      headlineGold: "Sealed Bottle.",
      desc: "A simple process, from carefully selected oilseeds to wood pressing, filling, and sealing — without unnecessary processing steps.",

      steps: [
        {
          step: "Step 01",
          icon: "🌱",
          title: "Carefully Selected Seeds",
          desc: "We select oilseeds based on their quality, condition, and suitability for making oil. Each batch is checked before pressing.",
          image: "/methods/hand-picked-seeds.png",
          alt: "Hands holding seeds",
          reverse: false,
          tested: "Selected · Checked · Prepared",
        },
        {
          step: "Step 02",
          icon: "🪵",
          title: "Mechanical Wood Pressing",
          desc: "The seeds are pressed using our mechanical wood press, operating at approximately 18–19 RPM. Oil is extracted through mechanical pressure in a slow pressing process.",
          image: "/methods/wooden-ghani.jpeg",
          alt: "Traditional wooden ghani press",
          reverse: true,
        },
        {
          step: "Step 03",
          icon: "🫙",
          title: "Oil Collection",
          desc: "Once pressed, the extracted oil is collected directly from the pressing process without filtration.",
          image: "/methods/wooden-ghani.jpeg",
          alt: "Lab testing oil purity",
          reverse: false,
        },
        {
          step: "Step 04",
          icon: "📦",
          title: "Filled & Sealed",
          desc: "The finished oil is filled and sealed in our facility, then packed and prepared for your kitchen.",
          image: "/methods/wooden-ghani.jpeg",
          alt: "Glass bottles of pressed oil",
          reverse: true,
        },
      ],
    },
    SideBySide: {
      icon: "✦",
      badge: "Side By Side",
      badge1Icon: "🌿",
      badge1: "TRADITIONAL",
      badge2Icon: "⚙",
      badge2: "INDUSTRIAL",
      headline1: "One is",
      headline2: "The other is",
      headlineGold: "Crafted.",
      headlineCross: "Manufactures.",
      desc: "Look closer. Every step of how oil is made shapes what reaches your kitchen.",
      subtitle1: "The Nityagro Way",
      subHeading1: "Wood-Pressed",
      subHeading2: "Refined-Multiple Processing Steps",
      subDesc1: "Slow. Mechanical. Deliberate. Our oilseeds are pressed using a mechanical wood press operating at approximately 18–19 RPM. The oil is extracted through mechanical pressure, without solvent extraction.",
      subDesc2: "Fast. Processed. Standardised. Refined oils may go through several industrial processing stages, including refining, bleaching, and deodorisation, depending on the production method.",
      image1: "/methods/wood-pressed-oil.jpeg",
      image2: "/methods/industrial-factory.png",
    },
  },

  "cold-pressed": {
    Banner: {
      image: "/banners/banner-cold-pressed.jpeg",
      title: "Cold Pressed",
    },
    ColdPressedFlour: {
      title: "Cold Pressed Flour",
      description: "Authentic Goodness in Every Bundle",
      badge: "OUR METHODS · COLD PRESSED FLOUR",
      headline1: "Pressed slow.",
      headline2: "Poured",
      headlineGold: "pure.",
      desc: "For four generations, we have pressed oil the way our grandmothers did — in wooden ghanis, with patience, and without a drop of chemistry. This is how we make every bottle.",
      btnPrimary: "Explore the Process",
      btnSecondary: "Shop Cold Pressed Oils",
      image: "/methods/wood-pressed-oil.jpg",
      stats: [
        { value: "40°C", label: "Max press temp" },
        { value: "100%", label: "Chemical free" },
        { value: "4 Gen", label: "Of craft" },
      ],
    },
    SeedToBottle: {
      title: "Four Steps · Zero Shortcuts",
      headline1: "From seed to ",
      headlineGold: "sealed bottle.",
      desc: "Every step happens within our own facility, by hands we know, in time measured by season — not by quarter.",

      tested: "Traditional · Time-Honoured · Tested",
      steps: [
        {
          step: "Step 01",
          icon: "🌱",
          title: "Hand-Picked Seeds",
          desc: "We source single-origin groundnut, sesame, coconut and mustard seeds directly from certified organic farms across India — sun-dried and inspected by hand.",
          image: "/methods/hand-picked-seeds.png",
          alt: "Hands holding seeds",
          reverse: false,
        },
        {
          step: "Step 02",
          icon: "⚙️",
          title: "Traditional Wooden Ghani",
          desc: "Seeds are crushed slowly in heritage wooden kolhus made from neem and sheesham. The press turns under 30 RPM, never letting temperatures cross 40°C.",
          image: "/methods/wooden-ghani.jpeg",
          alt: "Traditional wooden ghani press",
          reverse: true,
        },
        {
          step: "Step 03",
          icon: "🛡️",
          title: "Lab-Tested Purity",
          desc: "Every batch is tested in-house and by independent FSSAI-certified labs for nutrient retention, peroxide value and chemical-free purity before bottling.",
          image: "/methods/wooden-ghani.jpeg",
          alt: "Lab testing oil purity",
          reverse: false,
        },
        {
          step: "Step 04",
          icon: "📦",
          title: "Sealed in Glass",
          desc: "Filtered through unbleached cotton and bottled the same day in dark glass — protecting the natural aroma, antioxidants and golden colour from light.",
          image: "/methods/wooden-ghani.jpeg",
          alt: "Glass bottles of pressed oil",
          reverse: true,
        },
      ],
    },
    SideBySide: {
      icon: "✦",
      badge: "Side By Side",
      badge1Icon: "🌿",
      badge1: "TRADITIONAL",
      badge2Icon: "⚙",
      badge2: "INDUSTRIAL",
      headline1: "One is",
      headline2: "The other is",
      headlineGold: "Crafted.",
      headlineCross: "Manufactures.",
      desc: "Look closer. Every step of how oil is made shapes what reaches your kitchen.",
      subtitle1: "The Nityagro Way",
      subHeading1: "Cold-Pressed",
      subHeading2: "Refined",
      subDesc1: "Slow. Quiet. Patient. A wooden ghani turning under 30 RPM, the way it has for four generations — coaxing oil out, never forcing it.",
      subDesc2: "Fast. Hot. Chemical. Steel expellers spinning at 1500 RPM, hexane baths and bleaching clay — engineered for shelf life, not for you",
      image1: "/methods/wood-pressed-oil.jpeg",
      image2: "/methods/industrial-factory.png",
    },
  },

  "stone-pressed": {
    Banner: {
      image: "/banners/banner-stone-pressed.png",
      title: "STONE-PROCESSED FLOURS & SPICES",
    },
    ColdPressedFlour: {
      title: "STONE-PROCESSED FLOURS & SPICES",
      description: "Simple Food. Traditional Methods.",
      badge: "OUR METHODS · STONE PRESSED",
      headline1: "Ground the ",
      headline2: "traditional ",
      headlineGold: "way",
      desc: "Our flours and spices are made using traditional stone-based methods. From grains to flour and whole spices to powder, the process is kept simple and focused on the food itself.",
      btnPrimary: "Explore the Process",
      btnSecondary: "SHOP FLOURS & SPICES",

      image: "/methods/wood-pressed-oil.jpg",
      stats: [
        { value: "STONE GROUND", label: "Traditional stone processing" },
        { value: "WHOLE GRAINS", label: "Processed from selected grains" },
        { value: "WHOLE SPICES", label: "Ground from whole spices" },
        { value: "NO ADDED PRESERVATIVES", label: "Nothing extra added" },
      ],
    },
    SeedToBottle: {
      title: "Four Steps ",
      headline1: "From Grain & ",
      headlineGold: "Spice to Your Kitchen.",
      desc: "A simple process — from selecting the raw material to stone processing, packing, and sealing the finished product.",

      tested: "Traditional · Time-Honoured · Tested",
      steps: [
        {
          step: "Step 01",
          icon: "🌾",
          title: "Selected Raw Materials",
          desc: "We select grains and spices based on their quality, condition, and suitability for processing. Each batch is checked before it enters production.",
          image: "/methods/hand-picked-seeds.png",
          alt: "Hands holding seeds",
          reverse: false,
        },
        {
          step: "Step 02",
          icon: "⚙️",
          title: "Stone Processing",
          desc: "Grains are processed into flour and whole spices are processed into powder using traditional stone-based methods.",
          image: "/methods/wooden-ghani.jpeg",
          alt: "Traditional wooden ghani press",
          reverse: true,
        },
        {
          step: "Step 03",
          icon: "🫙",
          title: "Kept Simple",
          desc: "Every batch is tested in-house and by independent FSSAI-certified labs for nutrient retention, peroxide value and chemical-free purity before bottling.",
          image: "/methods/wooden-ghani.jpeg",
          alt: "Lab testing oil purity",
          reverse: false,
        },
        {
          step: "Step 04",
          icon: "📦",
          title: "Packed & Sealed",
          desc: "Once processed, the finished flour and spices are packed and sealed carefully before making their way to your kitchen.",
          image: "/methods/wooden-ghani.jpeg",
          alt: "Glass bottles of pressed oil",
          reverse: true,
        },
      ],
    },
    SideBySide: {
      icon: "✦",
      badge: "Side By Side",
      badge1Icon: "🌿",
      badge1: "TRADITIONAL",
      badge2Icon: "⚙",
      badge2: "INDUSTRIAL",
      headline1: "One way is",
      headline2: "The other takes its time.",
      headlineGold: "faster.",
      headlineCross: "Manufactures.",
      desc: "The way food is processed matters. Traditional stone processing takes a different approach — one built around a slower, simpler way of turning grains and whole spices into everyday foods.",
      subtitle1: "The Nityagro Way",
      subHeading1: "Stone-Pressed",
      subHeading2: "Refined",
      subDesc1: "Slow. Simple. Traditional. Grains and whole spices are processed using traditional stone-based methods to make flour and spice powders. Stone Ground · Traditional Method · Simple Processing",
      subDesc2: "Fast. High-Volume. Standardised. Industrial milling commonly uses high-speed machinery designed for large-scale production and consistent output.High Volume · High Speed · Standardised",
      image1: "/methods/wood-pressed-oil.jpeg",
      image2: "/methods/industrial-factory.png",
    },
  },
};
