const BASE_PRODUCTS = [
  {
    name: "Red Chilli Powder",
    category: "Spices",
    image: "/products/red-chilli.png",
    badge: "Best Seller",
    discount: "BES\n30%\nOFF",
    price: 250,
    rating: 4,
    reviews: 711,
  },
  {
    name: "Gran (Chickpea) Flour",
    category: "Flours",
    image: "/products/chickpea-flour.png",
    badge: null,
    discount: "BES\n30%\nOFF",
    price: 250,
    rating: 4,
    reviews: 711,
  },
  {
    name: "Jaggery Powder",
    category: "Jaggery",
    image: "/products/jaggery1.png",
    badge: "Best Seller",
    discount: null,
    price: 250,
    rating: 3,
    reviews: 711,
  },
  {
    name: "Red Chilli Powder",
    category: "Spices",
    image: "/products/red-chilli1.png",
    badge: null,
    discount: null,
    price: 250,
    rating: 4,
    reviews: 711,
  },
  {
    name: "Yellow Mustard Oil",
    category: "Oils",
    image: "/products/mustard-oil.png",
    badge: "Best Seller",
    discount: "BES\n30%\nOFF",
    price: 499,
    rating: 4.5,
    reviews: 148,
  },
  {
    name: "Sattu Flour",
    category: "Sattu",
    image: "/products/chickpea-flour.png",
    badge: null,
    discount: "BES\n30%\nOFF",
    price: 280,
    rating: 4,
    reviews: 203,
  },
  {
    name: "Daliya Flour",
    category: "Daliya",
    image: "/products/mustard-oil.png",
    badge: null,
    discount: "BES\n30%\nOFF",
    price: 260,
    rating: 4,
    reviews: 176,
  },
  {
    name: "Jaggery Powder",
    category: "Jaggery",
    image: "/products/jaggery1.png",
    badge: "Best Seller",
    discount: null,
    price: 250,
    rating: 3,
    reviews: 711,
  },
  {
    name: "Red Chilli Powder",
    category: "Spices",
    image: "/products/red-chilli1.png",
    badge: null,
    discount: null,
    price: 250,
    rating: 4,
    reviews: 711,
  },
  {
    name: "Yellow Mustard Oil",
    category: "Oils",
    image: "/products/mustard-oil.png",
    badge: null,
    discount: null,
    price: 499,
    rating: 4.5,
    reviews: 148,
  },
];

export const ALL_PRODUCTS = Array.from({ length: 35 }, (_, index) => {
  const product = BASE_PRODUCTS[index % BASE_PRODUCTS.length];

  return {
    id: index + 1,
    ...product,
    images: [
      product.image,
      "/products/red-chilli.png",
      "/products/chickpea-flour.png",
      "/products/jaggery1.png",
    ],
  };
});
